/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
static yyconst short int yy_accept[325] =
    {   0,
       16,   16,   28,   26,    6,    1,   26,   26,   16,   19,
       26,   16,   16,   22,   16,   16,   13,    6,    8,   17,
        8,   11,   26,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   26,    0,    0,   12,
       18,    0,    0,   16,   13,    0,    0,   19,    8,    0,
        2,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   10,   11,    7,   11,   11,   11,   11,   11,
       19,   15,    0,    0,   14,    0,   14,    2,    2,    2,
       11,    7,    9,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    0,    2,    0,

        2,   11,   11,    9,   11,   21,   10,   11,    0,   11,
       20,   11,   11,    4,   11,    0,    2,   11,    5,   11,
        0,    4,    0,   11,   11,   11,   11,    0,    2,   11,
       11,    0,    0,    0,   11,    5,    9,   24,    3,   11,
       11,   10,    0,    0,   11,   11,    5,    0,    0,   11,
       11,    0,    0,    0,   11,   23,    0,    0,   11,   23,
        0,    0,    0,    0,   11,   23,    0,    0,    0,    0,
       11,   23,    0,    0,    0,    0,   11,   23,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,   23,    0,
        0,    0,    0,    0,    0,    0,    0,   11,   23,    0,

        0,    0,    0,    0,    0,    0,   11,   23,    0,    0,
        0,    0,    0,   11,   23,    0,    0,    0,   25,    0,
        0,   11,   23,    0,    0,    0,    0,   11,   23,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,   23,
        0,    0,    0,    0,    0,    0,    0,    0,   11,   23,
        0,    0,    0,    0,    0,    0,    0,   11,   23,    0,
        0,    0,    0,    0,   11,   23,    0,    0,    0,   11,
       23,    0,    0,   11,   23,    0,    0,   11,   23,    0,
        0,   11,   23,    0,    0,   11,   23,    0,    0,   11,
       23,    0,    0,   11,   23,    0,    0,   11,   23,    0,

        0,   23,    0,    0,   23,    0,    0,   23,    0,    0,
       23,    0,    0,   23,    0,   23,    0,   23,    0,   23,
        0,   23,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
        1,   24,    1,   25,   23,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   23,   35,   36,   23,   37,
       38,   23,   23,   39,   40,   41,   42,   43,   44,   45,
       23,   23,   46,   47,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    1,
        1,    1,    6,    1,    1,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[459] =
    {   0,
        0,    0,  829,  830,  830,  830,  824,  822,  805,  804,
      800,   38,   33,  830,   34,  802,   41,  830,   32,  801,
       39,    0,  800,  783,   23,   30,  789,  782,   38,   35,
      778,  786,  774,  775,  780,  774,   44,  807,  805,  804,
      830,  800,   59,  796,   58,   65,   69,  785,  830,  784,
       63,    0,  775,  766,  772,  775,  763,  771,  758,  761,
      757,  758,    0,   46,    0,   52,  755,  751,  758,  752,
      830,  830,  782,  772,   72,   78,  771,    0,    0,   89,
        0,    0,    0,  761,  747,  744,  781,  753,  742,  778,
      752,  776,  742,  735,  742,  745,  738,  756,   92,  752,

       95,    0,  736,    0,  736,  830,  766,  738,    0,  726,
      830,  727,  728,    0,  734,  743,   96,    0,    0,  725,
      727,    0,  757,  725,  721,  689,  708,  681,   97,    0,
      649,  650,  635,  654,  607,    0,    0,  830,  613,    0,
      591,  830,  572,  594,  548,    0,    0,  570,  558,  546,
        0,    0,  534,    0,    0,    0,  522,   97,    0,    0,
      508,   98,  497,  101,    0,    0,  492,  473,  108,  105,
        0,    0,  468,  110,  126,  116,    0,    0,  456,  167,
       93,  111,   95,  112,  114,  113,  128,    0,    0,  444,
      120,  123,  130,  124,  125,  128,  136,    0,    0,  430,

      138,  133,  137,  142,  146,  158,    0,    0,  426,  171,
      148,  149,  176,    0,    0,  414,  168,  179,  170,  136,
      184,    0,    0,  406,  180,  226,  196,    0,    0,  400,
      272,  178,  182,  194,  190,  192,  199,  205,    0,    0,
      394,  209,  213,  193,  222,  211,  201,  242,    0,    0,
      388,  261,  233,  242,  245,  215,  253,    0,    0,  382,
      270,  248,  257,  274,    0,    0,  356,  266,  282,    0,
        0,  348,  283,    0,    0,  342,  286,    0,    0,  338,
      294,    0,    0,  335,  299,    0,    0,  298,  301,    0,
        0,  285,  310,    0,    0,  284,  314,  830,    0,  281,

      318,    0,  265,  319,    0,  221,  321,    0,  219,  322,
        0,  210,  323,    0,  326,    0,  330,    0,  331,    0,
      333,  830,  334,  830,  343,  349,  351,  357,  359,  365,
      367,  373,  375,  185,  377,  381,  383,  387,  389,  393,
      395,  399,  401,  157,  405,   64,  407,  409,  413,  417,
      419,  421,  425,  431,  435,  437,  439,  443,  447,  449,
      451,  455,  459,  461,  463,  467,  471,  473,  475,  479,
      483,  485,  487,  491,  495,  497,  499,  503,  509,  513,
      515,  517,  521,  525,  527,  529,  533,  537,  539,  541,
      545,  549,  551,  553,  557,  561,  563,  565,  569,  573,

      575,  577,  581,  585,  587,  589,  593,  597,  599,  601,
      605,  609,  611,  613,  617,  621,  623,  625,  629,  633,
      635,  637,  641,  645,  647,  649,  653,  657,  659,  661,
      665,  669,  671,  673,  677,  681,  683,  687,  691,  693,
      697,  701,  703,  707,  711,  713,  717,  721,  723,  727,
      729,  733,  735,  739,  741,  745,  747,  751
    } ;

static yyconst short int yy_def[459] =
    {   0,
      324,    1,  324,  324,  324,  324,  324,  325,  324,  324,
      326,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  327,  324,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  324,  324,  325,  325,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      328,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      324,  324,  324,  324,  324,  324,  324,  328,  328,  330,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  324,  330,  332,

      330,  333,  333,  333,  333,  324,  333,  333,  334,  333,
      324,  333,  333,  333,  333,  332,  330,  335,  335,  335,
      324,  335,  336,  335,  335,  335,  335,  332,  330,  337,
      337,  324,  324,  338,  337,  337,  337,  324,  332,  339,
      339,  324,  324,  340,  339,  341,  341,  324,  342,  341,
      343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
      353,  324,  354,  355,  356,  357,  358,  354,  354,  359,
      360,  361,  362,  354,  354,  363,  364,  365,  366,  354,
      354,  354,  354,  354,  354,  354,  367,  368,  369,  370,
      354,  354,  354,  354,  354,  354,  371,  372,  373,  374,

      354,  354,  354,  354,  354,  375,  376,  377,  378,  354,
      379,  354,  380,  381,  382,  383,  379,  379,  379,  354,
      384,  385,  386,  387,  379,  379,  388,  389,  390,  391,
      379,  379,  379,  379,  379,  379,  379,  392,  393,  394,
      395,  379,  379,  379,  379,  379,  379,  396,  397,  398,
      399,  379,  379,  379,  379,  379,  400,  401,  402,  403,
      379,  379,  379,  404,  405,  406,  407,  379,  408,  409,
      410,  411,  412,  413,  414,  415,  416,  417,  418,  419,
      420,  421,  422,  423,  424,  425,  426,  427,  428,  429,
      430,  431,  432,  433,  434,  435,  436,  324,  437,  438,

      439,  440,  441,  442,  443,  444,  445,  446,  447,  448,
      449,  324,  450,  451,  452,  453,  454,  455,  456,  457,
      458,  324,  324,    0,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324
    } ;

static yyconst short int yy_nxt[879] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,    4,    4,
       12,   13,   14,   15,    4,   16,   17,    4,   18,   19,
       20,   21,   22,    4,   23,   24,   25,   26,   27,   28,
       29,   22,   22,   30,   22,   22,   22,   31,   32,   33,
       34,   22,   22,   35,   36,    4,   37,    4,   44,   45,
       45,   48,   49,   41,   41,   46,   54,   45,   41,   49,
       51,   55,   56,   60,   41,   63,   72,   57,   71,  158,
       47,   64,   46,   92,   45,   61,   74,   93,   74,   62,
       76,   75,   76,   79,   80,   77,   83,   47,   75,   98,
      100,   98,   94,  100,   77,   73,  100,  100,  100,  162,

      162,   47,  169,  162,  169,  163,  163,  162,  101,  163,
      174,  101,  174,  163,  117,  129,  129,  169,  162,  169,
      169,  169,  169,  169,  163,  175,  191,  175,  180,  169,
      162,  193,  169,  169,  169,  169,  163,  169,  162,  169,
      210,  194,  169,  192,  163,  169,  169,  169,  202,  203,
      196,  169,  181,  182,  195,  169,  201,  218,  169,  183,
      162,  205,  156,  204,  184,  185,  163,  201,  186,  180,
      201,  201,  201,  210,  201,  212,  169,  218,  162,  218,
      169,  225,  225,  211,  163,  220,  162,  218,  218,  218,
      123,  218,  163,  181,  182,  219,  226,  226,  162,  218,

      183,  218,  218,  218,  163,  184,  185,  162,  218,  186,
      218,  242,  133,  163,  243,  219,  211,  219,  218,  245,
      218,  133,  218,  133,  218,  219,  219,  219,  231,  219,
      244,  218,  246,  252,  256,  218,  247,  219,  253,  219,
      219,  219,  218,  252,  162,  252,  219,  254,  219,  255,
      163,  218,  232,  233,  218,  162,  219,  218,  219,  234,
      219,  163,  219,  261,  235,  236,  218,  133,  237,  219,
      218,  252,  261,  219,  231,  218,  162,  252,  263,  218,
      219,  218,  163,  133,  162,  162,  133,  133,  162,  219,
      163,  163,  219,  268,  163,  219,  162,  252,  232,  233,

      133,  162,  163,  162,  219,  234,  262,  163,  219,  163,
      235,  236,  162,  219,  237,  262,  162,  219,  163,  219,
      162,  162,  163,  162,  162,  162,  163,  163,  162,  163,
      163,  163,  162,  162,  163,  162,  162,  133,  163,  163,
      133,  163,  163,   39,  133,   39,   39,   39,   39,   42,
      133,   42,   42,   42,   42,   52,   52,   78,  133,   78,
       78,   78,   78,   81,   81,   99,   99,   99,   99,   99,
       99,  102,  102,  100,  100,  100,  100,  100,  100,  118,
      118,  130,  130,  134,  133,  134,  134,  140,  140,  144,
      133,  144,  144,  146,  146,  149,  133,  149,  149,  151,

      151,  153,  133,  153,  153,  155,  155,  157,  133,  157,
      157,  159,  159,  160,  160,  161,  133,  161,  161,  164,
      164,  164,  164,  165,  165,  166,  166,  167,  133,  167,
      167,  168,  133,  168,  168,  168,  168,  170,  170,  170,
      170,  171,  171,  172,  172,  173,  133,  173,  173,  176,
      176,  176,  176,  177,  177,  178,  178,  179,  133,  179,
      179,  187,  187,  187,  187,  188,  188,  189,  189,  190,
      133,  190,  190,  197,  197,  197,  197,  198,  198,  199,
      199,  200,  169,  200,  200,  206,  206,  206,  206,  207,
      207,  208,  208,  209,  133,  209,  209,  213,  213,  213,

      213,  214,  214,  215,  215,  216,  169,  216,  216,  217,
      133,  217,  217,  217,  217,  221,  221,  221,  221,  222,
      222,  223,  223,  224,  133,  224,  224,  227,  227,  227,
      227,  228,  228,  229,  229,  230,  133,  230,  230,  238,
      238,  238,  238,  239,  239,  240,  240,  241,  154,  241,
      241,  248,  248,  248,  248,  249,  249,  250,  250,  251,
      133,  251,  251,  257,  257,  257,  257,  258,  258,  259,
      259,  260,  152,  260,  260,  264,  264,  264,  264,  265,
      265,  266,  266,  267,  150,  267,  267,  269,  269,  269,
      269,  270,  270,  271,  271,  272,  133,  272,  272,  273,

      273,  273,  273,  274,  274,  275,  275,  276,  148,  276,
      276,  277,  277,  277,  277,  278,  278,  279,  279,  280,
      147,  280,  280,  281,  281,  281,  281,  282,  282,  283,
      283,  284,  139,  284,  284,  285,  285,  285,  285,  286,
      286,  287,  287,  288,  145,  288,  288,  289,  289,  289,
      289,  290,  290,  291,  291,  292,  133,  292,  292,  293,
      293,  293,  293,  294,  294,  295,  295,  296,  143,  296,
      296,  297,  297,  297,  297,  298,  298,  299,  299,  300,
      142,  300,  300,  301,  301,  301,  301,  302,  302,  303,
      141,  303,  303,  304,  304,  304,  304,  305,  305,  306,

      139,  306,  306,  307,  307,  307,  307,  308,  308,  309,
      138,  309,  309,  310,  310,  310,  310,  311,  311,  312,
      137,  312,  312,  313,  313,  313,  313,  314,  314,  315,
      315,  315,  315,  316,  316,  317,  317,  317,  317,  318,
      318,  319,  319,  319,  319,  320,  320,  321,  321,  321,
      321,  322,  322,  323,  323,  323,  323,  136,  135,  133,
      132,  131,  128,  127,  126,  125,  124,  122,  121,  120,
      119,  116,   77,  115,  114,  113,  112,  104,  111,  110,
      109,  108,  107,  106,  105,  104,  103,   77,   75,   72,
       82,   97,   96,   95,   91,   90,   89,   88,   87,   86,

       85,   84,   83,   82,   49,   41,   44,   72,   40,   40,
       49,   70,   69,   68,   67,   66,   65,   59,   58,   53,
       41,   50,   41,   43,   41,   41,   40,   38,  324,    3,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324
    } ;

static yyconst short int yy_chk[879] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   12,   13,
       15,   19,   19,   13,   15,   17,   25,   17,   12,   21,
       21,   25,   26,   29,   37,   30,   43,   26,   37,  346,
       17,   30,   45,   64,   45,   29,   46,   66,   46,   29,
       47,   46,   47,   51,   51,   47,   64,   45,   75,   76,
       80,   76,   66,   99,   76,   43,  101,  117,  129,  158,

      162,   75,  181,  164,  183,  158,  162,  170,   80,  164,
      169,   99,  174,  170,  101,  117,  129,  169,  176,  174,
      182,  184,  186,  185,  176,  169,  181,  174,  175,  191,
      187,  183,  192,  194,  195,  175,  187,  196,  197,  193,
      201,  184,  202,  182,  197,  220,  203,  201,  192,  194,
      186,  204,  175,  175,  185,  205,  191,  211,  212,  175,
      206,  196,  344,  195,  175,  175,  206,  220,  175,  180,
      193,  202,  203,  210,  205,  204,  180,  217,  213,  219,
      210,  218,  225,  201,  213,  212,  221,  232,  218,  225,
      334,  233,  221,  180,  180,  211,  218,  225,  227,  235,

      180,  236,  244,  234,  227,  180,  180,  238,  237,  180,
      247,  232,  312,  238,  233,  217,  210,  219,  242,  235,
      246,  309,  243,  306,  256,  232,  218,  225,  226,  233,
      234,  245,  236,  244,  247,  226,  237,  235,  243,  236,
      244,  234,  253,  256,  248,  242,  237,  245,  247,  246,
      248,  254,  226,  226,  255,  257,  242,  262,  246,  226,
      243,  257,  256,  252,  226,  226,  263,  303,  226,  245,
      252,  253,  261,  226,  231,  268,  264,  254,  255,  261,
      253,  231,  264,  300,  269,  273,  296,  292,  277,  254,
      269,  273,  255,  263,  277,  262,  281,  268,  231,  231,

      288,  285,  281,  289,  263,  231,  252,  285,  252,  289,
      231,  231,  293,  268,  231,  261,  297,  261,  293,  231,
      301,  304,  297,  307,  310,  313,  301,  304,  315,  307,
      310,  313,  317,  319,  315,  321,  323,  284,  317,  319,
      280,  321,  323,  325,  276,  325,  325,  325,  325,  326,
      272,  326,  326,  326,  326,  327,  327,  328,  267,  328,
      328,  328,  328,  329,  329,  330,  330,  330,  330,  330,
      330,  331,  331,  332,  332,  332,  332,  332,  332,  333,
      333,  335,  335,  336,  260,  336,  336,  337,  337,  338,
      251,  338,  338,  339,  339,  340,  241,  340,  340,  341,

      341,  342,  230,  342,  342,  343,  343,  345,  224,  345,
      345,  347,  347,  348,  348,  349,  216,  349,  349,  350,
      350,  350,  350,  351,  351,  352,  352,  353,  209,  353,
      353,  354,  200,  354,  354,  354,  354,  355,  355,  355,
      355,  356,  356,  357,  357,  358,  190,  358,  358,  359,
      359,  359,  359,  360,  360,  361,  361,  362,  179,  362,
      362,  363,  363,  363,  363,  364,  364,  365,  365,  366,
      173,  366,  366,  367,  367,  367,  367,  368,  368,  369,
      369,  370,  168,  370,  370,  371,  371,  371,  371,  372,
      372,  373,  373,  374,  167,  374,  374,  375,  375,  375,

      375,  376,  376,  377,  377,  378,  163,  378,  378,  379,
      161,  379,  379,  379,  379,  380,  380,  380,  380,  381,
      381,  382,  382,  383,  157,  383,  383,  384,  384,  384,
      384,  385,  385,  386,  386,  387,  153,  387,  387,  388,
      388,  388,  388,  389,  389,  390,  390,  391,  150,  391,
      391,  392,  392,  392,  392,  393,  393,  394,  394,  395,
      149,  395,  395,  396,  396,  396,  396,  397,  397,  398,
      398,  399,  148,  399,  399,  400,  400,  400,  400,  401,
      401,  402,  402,  403,  145,  403,  403,  404,  404,  404,
      404,  405,  405,  406,  406,  407,  144,  407,  407,  408,

      408,  408,  408,  409,  409,  410,  410,  411,  143,  411,
      411,  412,  412,  412,  412,  413,  413,  414,  414,  415,
      141,  415,  415,  416,  416,  416,  416,  417,  417,  418,
      418,  419,  139,  419,  419,  420,  420,  420,  420,  421,
      421,  422,  422,  423,  135,  423,  423,  424,  424,  424,
      424,  425,  425,  426,  426,  427,  134,  427,  427,  428,
      428,  428,  428,  429,  429,  430,  430,  431,  133,  431,
      431,  432,  432,  432,  432,  433,  433,  434,  434,  435,
      132,  435,  435,  436,  436,  436,  436,  437,  437,  438,
      131,  438,  438,  439,  439,  439,  439,  440,  440,  441,

      128,  441,  441,  442,  442,  442,  442,  443,  443,  444,
      127,  444,  444,  445,  445,  445,  445,  446,  446,  447,
      126,  447,  447,  448,  448,  448,  448,  449,  449,  450,
      450,  450,  450,  451,  451,  452,  452,  452,  452,  453,
      453,  454,  454,  454,  454,  455,  455,  456,  456,  456,
      456,  457,  457,  458,  458,  458,  458,  125,  124,  123,
      121,  120,  116,  115,  113,  112,  110,  108,  107,  105,
      103,  100,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   77,   74,   73,
       70,   69,   68,   67,   62,   61,   60,   59,   58,   57,

       56,   55,   54,   53,   50,   48,   44,   42,   40,   39,
       38,   36,   35,   34,   33,   32,   31,   28,   27,   24,
       23,   20,   16,   11,   10,    9,    8,    7,    3,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "assignment.l"
#define INITIAL 0
#line 2 "assignment.l"
#include <bits/stdc++.h>
using namespace std;

string x;
int count_of_identifiers = 0;
int count_of_keywords = 0;
int count_of_statements = 0;
int inc = 0;
int inf = 0;

void print(string comment, string message) {
    cout << "input : " << message << "\n";
    cout << "token : " << comment << "\n\n";
}
#line 705 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 48 "assignment.l"


#line 859 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 325 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 830 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "assignment.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "assignment.l"
{x = yytext; print("singleline comment", x);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "assignment.l"
{x = yytext; print("multiline comment", x);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "assignment.l"
{x = yytext; print("bin",  x);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "assignment.l"
{x = yytext; print("keyword", x); count_of_keywords++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "assignment.l"
{count_of_statements++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "assignment.l"
{x = yytext; print("logical_operator",  x);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "assignment.l"
{x = yytext; print("comparison operator",  x);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "assignment.l"
{x = yytext; print("datatype",  x); count_of_keywords++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "assignment.l"
{x = yytext;  print("if condition", x); inf++;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "assignment.l"
{x = yytext; print("identifier",  x); count_of_identifiers++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "assignment.l"
{x = yytext; print("string",  x);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "assignment.l"
{x = yytext; print("int",  x);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "assignment.l"
{x = yytext; print("real",  x);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "assignment.l"
{x = yytext; print("char",  x);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "assignment.l"
{x = yytext; print("algebric_op",  x);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "assignment.l"
{x = yytext; print("assignment operator",  x);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "assignment.l"
{x = yytext; print("operation with assignment",  x);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "assignment.l"
{x = yytext; print("bitwise operator",  x);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "assignment.l"
{x = yytext; print("indec_operator",  x); inc++;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "assignment.l"
{x = yytext; print("indec_operator",  x); inc++;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "assignment.l"
{x = yytext; print("comma operator",  x);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "assignment.l"
{x = yytext; print("for loop", x);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "assignment.l"
{x = yytext; print("while loop", x); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "assignment.l"
{x = yytext; print("subroutine", x);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "assignment.l"
{}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "assignment.l"
ECHO;
	YY_BREAK
#line 1077 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 325 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 325 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 324);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 76 "assignment.l"


int yywrap() {
    return 1;
}

void replaceNewlinesWithWhitespace(const std::string filename) {
    std::ifstream inputFile(filename);
    if (!inputFile) {
        std::cerr << "Error: Unable to open input file." << std::endl;
        return;
    }
    std::string content;
    std::string line;
    while (std::getline(inputFile, line)) {
        content += line + " ";
    }
    inputFile.close();
    std::ofstream outputFile("temp");
    if (!outputFile) {
        std::cerr << "Error: Unable to open output file." << std::endl;
        return;
    }
    outputFile << content;
    outputFile.close();
}

int main() {
    yyin = freopen("input.txt", "r", stdin);
    cout << "Evaluation is running...\n";
    yylex();
    cout << "Total identifiers found: " << count_of_identifiers << "\n";
    cout << "Total keywords found   : " << count_of_keywords << "\n";
    cout << "Total statements found : " << count_of_statements << "\n";
    cout << "Total if-else statements found : " << inf << "\n";
    return 0;
}
